import { config } from "dotenv";
import { sql } from "drizzle-orm";
import { getDb } from "./index";
import { academicTypes, knowledgeFields } from "./schema";

config({ path: ".env.local" });

/**
 * Canonical taxonomies from Brief/Architecture.
 * Slug is the stable identity; UUID is generated by PostgreSQL.
 * "Maestría profesional" maps to Maestría and "Máster ejecutivo" to Máster.
 */
const ACADEMIC_TYPES = [
  { slug: "tecnico", name: "Técnico", sortOrder: 10 },
  { slug: "diplomado", name: "Diplomado", sortOrder: 20 },
  { slug: "especialista", name: "Especialista", sortOrder: 30 },
  { slug: "mision-academica", name: "Misión académica", sortOrder: 40 },
  { slug: "seminario", name: "Seminario", sortOrder: 50 },
  { slug: "programa-ejecutivo", name: "Programa ejecutivo", sortOrder: 60 },
  { slug: "bachillerato", name: "Bachillerato", sortOrder: 70 },
  { slug: "licenciatura", name: "Licenciatura", sortOrder: 80 },
  { slug: "maestria", name: "Maestría", sortOrder: 90 },
  { slug: "master", name: "Máster", sortOrder: 100 },
  { slug: "doctorado", name: "Doctorado", sortOrder: 110 },
] as const;

const KNOWLEDGE_FIELDS = [
  {
    slug: "gobierno-riesgos-cumplimiento",
    name: "Gobierno, riesgos y cumplimiento",
    sortOrder: 10,
  },
  {
    slug: "direccion-liderazgo-estrategia",
    name: "Dirección, liderazgo y estrategia",
    sortOrder: 20,
  },
  {
    slug: "finanzas-tributacion-mercados",
    name: "Finanzas, tributación y mercados",
    sortOrder: 30,
  },
  {
    slug: "derecho-sector-publico-regulacion",
    name: "Derecho, sector público y regulación",
    sortOrder: 40,
  },
  {
    slug: "tecnologia-datos-inteligencia-artificial",
    name: "Tecnología, datos e inteligencia artificial",
    sortOrder: 50,
  },
  {
    slug: "operaciones-seguros-mercados-especialidad",
    name: "Operaciones, seguros y mercados de especialidad",
    sortOrder: 60,
  },
] as const;

async function seed() {
  const db = getDb();

  await db
    .insert(academicTypes)
    .values([...ACADEMIC_TYPES])
    .onConflictDoUpdate({
      target: academicTypes.slug,
      set: {
        name: sql`excluded.name`,
        sortOrder: sql`excluded.sort_order`,
      },
    });

  await db
    .insert(knowledgeFields)
    .values([...KNOWLEDGE_FIELDS])
    .onConflictDoUpdate({
      target: knowledgeFields.slug,
      set: {
        name: sql`excluded.name`,
        sortOrder: sql`excluded.sort_order`,
      },
    });

  const typeRows = await db
    .select({
      slug: academicTypes.slug,
      name: academicTypes.name,
      sortOrder: academicTypes.sortOrder,
    })
    .from(academicTypes)
    .orderBy(academicTypes.sortOrder);

  const fieldRows = await db
    .select({
      slug: knowledgeFields.slug,
      name: knowledgeFields.name,
      sortOrder: knowledgeFields.sortOrder,
    })
    .from(knowledgeFields)
    .orderBy(knowledgeFields.sortOrder);

  console.log(`academic_types=${typeRows.length}`);
  for (const row of typeRows) {
    console.log(`${row.sortOrder}\t${row.slug}\t${row.name}`);
  }

  console.log(`knowledge_fields=${fieldRows.length}`);
  for (const row of fieldRows) {
    console.log(`${row.sortOrder}\t${row.slug}\t${row.name}`);
  }
}

seed().catch((error) => {
  console.error(error instanceof Error ? error.message : "Seed failed.");
  process.exit(1);
});
